-- Menu reale MōMA importato da leggimenu.it/menu/moma
-- Sostituisce i dati di esempio: piatti inclusi nella formula AYCE a prezzo 0
-- (il prezzo fisso a persona è gestito su orders.ayce_price_cents),
-- dolci/digestivi e bevande a prezzo pieno (esclusi dalla formula AYCE).

-- 1) Rimuove i dati di esempio precedenti (inclusi ordini di test che referenziano i vecchi piatti)
delete from order_items;
delete from orders;
update restaurant_tables set status = 'libero';
delete from menu_items;
delete from menu_categories;

-- 2) Categorie (cibo incluso in AYCE + dolci/digestivi + bevande, in un unico ordine)
insert into menu_categories (name, slug, sort_order) values
  ('Antipasti', 'antipasti', 1),
  ('Tempure - Fritti con Japan Panko (4 pz)', 'tempure-fritti-con-japan-panko-4-pz', 2),
  ('Creazioni Ramiro Reinoso (4 pz)', 'creazioni-ramiro-reinoso-4-pz', 3),
  ('Uramaki (8pz)', 'uramaki-8pz', 4),
  ('Tartare', 'tartare', 5),
  ('Sashimi - (4pz)', 'sashimi-4pz', 6),
  ('Nigiri - (1pz)', 'nigiri-1pz', 7),
  ('Gunkan - (1pz)', 'gunkan-1pz', 8),
  ('Hosomaki - (6pz)', 'hosomaki-6pz', 9),
  ('Gluten free', 'gluten-free', 10),
  ('Cucina', 'cucina', 11),
  ('Dolci e digestivi', 'dolci-e-digestivi', 12),
  ('Cocktail', 'cocktail', 13),
  ('Bevande e Birre', 'bevande-e-birre', 14),
  ('Vino bianco', 'vino-bianco', 15),
  ('Bollicine', 'bollicine', 16),
  ('Fine Pasto', 'fine-pasto', 17),
  ('Vini Rosati', 'vini-rosati', 18),
  ('Vino Rosso', 'vino-rosso', 19);

-- 3) Piatti
with cat as (select id, slug from menu_categories)
insert into menu_items (category_id, name, description, price_cents, menu_type, ayce_surcharge_cents, photo_url, allergens, tags, sort_order)
select c.id, v.name, v.description, v.price_cents, v.menu_type::menu_type, 0, v.photo_url, v.allergens, v.tags, v.sort_order
from (values
  ('antipasti', 'Taquito Gambero locale e burrata', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/taquit-gambero-locale-e-burrata.jpg', array['surgelati']::text[], array[]::text[], 1),
  ('antipasti', 'Taquito Salmone cotto, misticanza, salsa spicy e mandorle', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/taquit-salmone-cotto-misticanza-salsa-spicy-e-mandorle.jpg', array['abbattuti']::text[], array[]::text[], 2),
  ('antipasti', 'Taquito Tonno, guacamole e pomodorino', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/taquit-tonno-guacamole-e-pomodorino.jpg', array['abbattuti']::text[], array[]::text[], 3),
  ('antipasti', 'Alghe wakame', 'La walkame è un’alga ricca di proteine, amminoacidi essenziali, come il triptofano, che la rendono un alimento complementare alle tradizionali fonti di proteine vegetali, come legumi e cereali.', 0, 'ayce', null, array['surgelati']::text[], array['vegetariano','gluten_free']::text[], 4),
  ('antipasti', 'Edamame', 'Trattasi più precisamente di frutti interi, quindi ancora chiusi, contenenti i semi verdi, leggermente immaturi, della pianta erbacea appartenente alla Famiglia Fabaceae, Genere Glycine e specie max.', 0, 'ayce', null, array['surgelati']::text[], array['vegetariano','gluten_free']::text[], 5),
  ('antipasti', 'Taquito Tonno spicy', 'Mini tacos con tartare di tonno piccante e cipollotto', 0, 'ayce', null, array[]::text[], array[]::text[], 6),
  ('antipasti', 'Taquito Salmone spicy', 'Mini tacos con tartare di salmone piccante e cipollotto', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/taquito-salmone-spicy.jpg', array[]::text[], array[]::text[], 7),
  ('antipasti', 'taquit pistacchio', 'taquit burrata, pistacchio e salsa teryaki', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/taquit-pistacchio.jpg', array[]::text[], array[]::text[], 8),
  ('tempure-fritti-con-japan-panko-4-pz', 'Involtino primavera 3 pz', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 1),
  ('tempure-fritti-con-japan-panko-4-pz', 'ravioli di pollo 2 pz', 'ravioli di pollo fritti in tempura', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 2),
  ('tempure-fritti-con-japan-panko-4-pz', 'Tempura di gamberoni', '', 0, 'ayce', null, array['surgelati']::text[], array[]::text[], 3),
  ('tempure-fritti-con-japan-panko-4-pz', 'Tempura fiori di zucca', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 4),
  ('tempure-fritti-con-japan-panko-4-pz', 'Hot Phila pistacchio', 'Interno: pesce del giorno Top: philadephia e pistacchio', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 5),
  ('tempure-fritti-con-japan-panko-4-pz', 'Hot Phila mandorle', 'Interno: pesce del giorno Top: philadephia e mandorle', 0, 'ayce', null, array[]::text[], array[]::text[], 6),
  ('tempure-fritti-con-japan-panko-4-pz', 'Hot Phila tartufo', 'Interno: pesce del giorno Top: philadephia e perlage di tartufo nero', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/hot-phila-tartufo.jpg', array[]::text[], array[]::text[], 7),
  ('tempure-fritti-con-japan-panko-4-pz', 'Hot Phila mix', 'Hosomaki fritto (interno: pesce del giorno) e top di philadelphia e gusti misti', 0, 'ayce', null, array[]::text[], array[]::text[], 8),
  ('tempure-fritti-con-japan-panko-4-pz', 'HotPhila con salsa al mango', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/hotphila-con-salsa-al-mango.jpg', array[]::text[], array[]::text[], 9),
  ('tempure-fritti-con-japan-panko-4-pz', 'HotPhila uova di salmone', 'Interno: pesce del giorno Top: philadephia e uova di salmone', 0, 'ayce', null, array[]::text[], array[]::text[], 10),
  ('tempure-fritti-con-japan-panko-4-pz', 'HotPhila Cipolla caramellata', 'Interno: pesce del giorno Top: philadeplhia e cipolla caramellata', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/hotphila-cipolla-caramellata.jpg', array[]::text[], array[]::text[], 11),
  ('tempure-fritti-con-japan-panko-4-pz', 'HotPhila con fragole', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/hotphila-con-fragole.jpg', array[]::text[], array[]::text[], 12),
  ('tempure-fritti-con-japan-panko-4-pz', 'Hot salmon', 'Interno: pesce del giorno Top: salmone speziato e teriyaki', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/hot-salmon.jpg', array[]::text[], array[]::text[], 13),
  ('tempure-fritti-con-japan-panko-4-pz', 'Patatine fritte', '', 0, 'ayce', null, array['surgelati']::text[], array['vegetariano']::text[], 14),
  ('tempure-fritti-con-japan-panko-4-pz', 'Ravioli di Verdure', '', 0, 'ayce', null, array[]::text[], array[]::text[], 15),
  ('creazioni-ramiro-reinoso-4-pz', 'Sashimi salmone special, perlage di tartufo e MōMA soy ( 3 pz )', 'Sashimi di salmone con perlage di tartufo e moma sauce ( Incluso nel menu all you can eat una porzione a persona ) *Disponibilità limitata* (disponibile solo a cena)', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/sashimi-salmone-special-perlage-di-tartufo-e-m-ma-soy-3-pz.jpg', array['abbattuti']::text[], array[]::text[], 1),
  ('creazioni-ramiro-reinoso-4-pz', 'Giulia Roll 4 pezzi', '-Gambero in tempura; -Maionese; -Cipollotto; -Avocado; -Cover di salmone condita; -Teriyaki. (disponibile solo a cena)', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/giulia-roll-4-pezzi.jpg', array['surgelati','abbattuti']::text[], array[]::text[], 2),
  ('creazioni-ramiro-reinoso-4-pz', 'Gunkan Octopus ( 1 pz )', 'Gunkan con cover di ricciola, tataki di polipo scottato con maionese giapponese e perlage di tartufo ( Ordinabile solo un porzione a persona ) *Disponibilità limitata* (disponibile solo a cena)', 0, 'ayce', null, array[]::text[], array[]::text[], 3),
  ('creazioni-ramiro-reinoso-4-pz', 'Futomaki Hot ( 10 pz )', 'Roll in tempura con Salmone, avocado , philadelphia e salsa teryaki Illimitato fino a esaurimento scorte (disponibile solo a cena)', 0, 'ayce', null, array[]::text[], array[]::text[], 4),
  ('creazioni-ramiro-reinoso-4-pz', 'Pachino roll 4 pezzi', 'Salmone, avocado, philadelphia, pomodoro secco e Perlage di tartufo nero (disponibile solo a cena)', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/pachino-roll-4-pezzi.jpg', array[]::text[], array[]::text[], 5),
  ('uramaki-8pz', 'Uramaki Flowers & Ama ebi (8pz)', 'Alga, Riso, fiori di zucca in tempura, philadelphia, avocado,teriyaki, stracciatella', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/uramaki-flowers-ama-ebi-8pz.jpg', array['abbattuti']::text[], array[]::text[], 1),
  ('uramaki-8pz', 'Spicy Salmon', '-Salmone; -Spicy; -Cipollotto; -Crunch; -Cover di salmone;', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/spicy-salmon.jpg', array['abbattuti']::text[], array['piccante']::text[], 2),
  ('uramaki-8pz', 'Spicy Katsuobushi Tuna', '-Tonno; -Spicy; -Cipollotto; -Crunch; -Katsuobushi.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/spicy-katsuobushi-tuna.jpg', array['abbattuti']::text[], array['piccante']::text[], 3),
  ('uramaki-8pz', 'Philadelphia Roll', '-Salmone; -Avocado; -Philadelphia.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/philadelphia-roll.jpg', array['abbattuti']::text[], array['gluten_free']::text[], 4),
  ('uramaki-8pz', 'White Lime', '-Gambero in tempura; -Maionese al lime; -Avocado; -Crunch; -Maionese al lime.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/white-lime.jpg', array['abbattuti']::text[], array[]::text[], 5),
  ('uramaki-8pz', 'Mae Roll', '-Gambero in tempura; -Maionese; -Patate americane fritte.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/mae-roll.jpg', array['surgelati']::text[], array[]::text[], 6),
  ('uramaki-8pz', 'Ebiten Roll (8pz)', 'gambero in tempura, avocado, tartare di mazzancolle cotte, teriyaki e crunch', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/ebiten-roll-8pz.jpg', array['surgelati']::text[], array[]::text[], 7),
  ('uramaki-8pz', 'Noto', 'Tonno, avocado, guacamole e pomodorini', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/noto.jpg', array['abbattuti']::text[], array[]::text[], 8),
  ('uramaki-8pz', 'Rainbow', 'avocado, cover di pesce mista', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/rainbow.jpg', array['abbattuti']::text[], array[]::text[], 9),
  ('uramaki-8pz', 'Salmon Roll', 'Salmone, avocado e sesamo', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/salmon-roll.jpg', array['abbattuti']::text[], array[]::text[], 10),
  ('uramaki-8pz', 'Tuna Roll', 'Tonno, avocado e sesamo', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/tuna-roll.jpg', array['abbattuti']::text[], array[]::text[], 11),
  ('uramaki-8pz', 'Tartufo roll', 'Salmone, avocado, philadelphia e perle di tartufo nero', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/tartufo-roll.jpg', array['abbattuti']::text[], array[]::text[], 12),
  ('uramaki-8pz', 'Caramel roll', 'Gambero in tempura, philadelphia, mango e cipolla caramellata', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/caramel-roll.jpg', array['abbattuti']::text[], array[]::text[], 13),
  ('uramaki-8pz', 'Salmon tempura', 'salmone in tempura, philadelphia, misticanza, mandorle e salsa teriyaki', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/salmon-tempura.jpg', array['abbattuti']::text[], array[]::text[], 14),
  ('uramaki-8pz', 'Crunch roll', 'salmone cotto, avocado, philadelphia, teriyaki e crunch', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/crunch-roll.jpg', array['surgelati']::text[], array[]::text[], 15),
  ('uramaki-8pz', 'Patrick roll', 'Tonno, zest di lime e mandorle', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/patrick-roll.jpg', array['abbattuti']::text[], array[]::text[], 16),
  ('uramaki-8pz', 'Kataifi Roll', 'Gambero in tempura, avocado, maionese, cover di salmone scottata, kataifi fritto', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/kataifi-roll.jpg', array['surgelati']::text[], array[]::text[], 17),
  ('uramaki-8pz', 'Turi roll', 'Salmone, avocado, philadelphia e cover di salmone scottata con salsa spicy', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/turi-roll.jpg', array['abbattuti']::text[], array[]::text[], 18),
  ('uramaki-8pz', 'Guacamole sake', 'Salmone, avocado, top di guacamole', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/guacamole-sake.jpg', array[]::text[], array['gluten_free']::text[], 19),
  ('uramaki-8pz', 'Ebi teriyaki', 'gambero in tempura, avocado, cover di salmone flambè e salsa teriyaki', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/ebi-teriyaki.jpg', array['abbattuti']::text[], array[]::text[], 20),
  ('uramaki-8pz', 'Teka Roll', 'Salmone, avocado, cover di pesce bianco e perle di tartufo nero', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/teka-roll.jpg', array['abbattuti']::text[], array[]::text[], 21),
  ('uramaki-8pz', 'Pepper Roll', 'Gambero in tempura, avocado, cover di pesce bianco, maionese al peperone affumicato flambè', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 22),
  ('uramaki-8pz', 'Turi Fire', 'Salmone cotto in salsa spicy ,philadelphia, avocado, cover di salmone con spicy scottato', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/turi-fire.jpg', array['abbattuti']::text[], array[]::text[], 23),
  ('tartare', 'Tartare salmone, crunch e MōMA guacamole', 'Disponibile solo a cena', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 1),
  ('tartare', 'Tartare tonno, stracciatella e zest di arancia', 'Disponibile solo a cena', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 2),
  ('sashimi-4pz', 'Sashimi salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/sashimi-salmone.jpg', array['abbattuti']::text[], array[]::text[], 1),
  ('sashimi-4pz', 'Sashimi tonno', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/sashimi-tonno.jpg', array['abbattuti']::text[], array[]::text[], 2),
  ('nigiri-1pz', 'Nigiri Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/nigiri-salmone.jpg', array['abbattuti']::text[], array[]::text[], 1),
  ('nigiri-1pz', 'Nigiri Tonno', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 2),
  ('nigiri-1pz', 'Special nigiri ricciola con perlage di tartufo nero', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/special-nigiri-ricciola-con-perlage-di-tartufo-nero.jpg', array['abbattuti']::text[], array[]::text[], 3),
  ('nigiri-1pz', 'Special Nigiri Salmone e uova di Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/special-nigiri-salmone-e-uova-di-salmone.jpg', array['abbattuti']::text[], array[]::text[], 4),
  ('nigiri-1pz', 'Nigiri Aburì Salmone e salsa spicy scottato', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/nigiri-aburi-salmone-e-salsa-spicy-scottato.jpg', array['abbattuti']::text[], array['piccante']::text[], 5),
  ('nigiri-1pz', 'Nigiri Ricciola', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/nigiri-ricciola.jpg', array[]::text[], array[]::text[], 6),
  ('nigiri-1pz', 'Nigiri ricciola flambè con maionese al peperone affumicato', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/nigiri-ricciola-flambe-con-maionese-al-peperone-affumicato.jpg', array['abbattuti']::text[], array[]::text[], 7),
  ('gunkan-1pz', 'Gunkan Ricciola Flambè', 'Ricciola, salsa fuji e tobiko', 0, 'ayce', null, array[]::text[], array[]::text[], 1),
  ('gunkan-1pz', 'Gunkan Tonno Flambé', 'Tonno, maionese, cover di tonno, scottato', 0, 'ayce', null, array[]::text[], array[]::text[], 2),
  ('gunkan-1pz', 'Gunkan salmone e Uova di Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gunkan-salmone-e-uova-di-salmone.jpg', array[]::text[], array[]::text[], 3),
  ('gunkan-1pz', 'Gunkan Philadelphia - salmone e top di tartare di salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gunkan-philadelphia-salmone-e-top-di-tartare-di-salmone.jpg', array[]::text[], array[]::text[], 4),
  ('gunkan-1pz', 'Gunkan Edi', 'Salmone, philadelphia, teriyaki,', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gunkan-edi.jpg', array['abbattuti']::text[], array[]::text[], 5),
  ('gunkan-1pz', 'Gunkan Fragola', 'Gunkan Fragola - Salmone, philadelphia, fragola e teriyaki', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gunkan-fragola.jpg', array['abbattuti']::text[], array[]::text[], 6),
  ('gunkan-1pz', 'Gunkan Mango', 'salmone, philadelphia e salsa mango', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gunkan-mango.jpg', array['abbattuti']::text[], array[]::text[], 7),
  ('hosomaki-6pz', 'Hosomaki Riso e Salmone', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 1),
  ('hosomaki-6pz', 'Hosomaki Riso e Tonno', '', 0, 'ayce', null, array[]::text[], array[]::text[], 2),
  ('hosomaki-6pz', 'Hosomaki Ricciola', '', 0, 'ayce', null, array[]::text[], array[]::text[], 3),
  ('hosomaki-6pz', 'Hosomaki Gambero in Tempura', '', 0, 'ayce', null, array[]::text[], array[]::text[], 4),
  ('hosomaki-6pz', 'Hosomaki Riso e Avocado', '', 0, 'ayce', null, array[]::text[], array[]::text[], 5),
  ('hosomaki-6pz', 'Hosomaki Riso e Mango', '', 0, 'ayce', null, array[]::text[], array[]::text[], 6),
  ('gluten-free', 'Tartare tonno, stracciatella e zest di arancia', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 1),
  ('gluten-free', 'Sashimi salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-sashimi-salmone.jpg', array['abbattuti']::text[], array[]::text[], 2),
  ('gluten-free', 'Sashimi tonno', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-sashimi-tonno.jpg', array['abbattuti']::text[], array[]::text[], 3),
  ('gluten-free', 'Nigiri Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-nigiri-salmone.jpg', array['abbattuti']::text[], array[]::text[], 4),
  ('gluten-free', 'Nigiri Tonno', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 5),
  ('gluten-free', 'Special nigiri ricciola con perlage di tartufo nero', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-special-nigiri-ricciola-con-perlage-di-tartufo-nero.jpg', array['abbattuti']::text[], array[]::text[], 6),
  ('gluten-free', 'Special Nigiri Salmone e uova di Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-special-nigiri-salmone-e-uova-di-salmone.jpg', array['abbattuti']::text[], array[]::text[], 7),
  ('gluten-free', 'Gunkan Tonno Flambé', 'Tonno, maionese, cover di tonno, scottato', 0, 'ayce', null, array[]::text[], array[]::text[], 8),
  ('gluten-free', 'Gunkan salmone e Uova di Salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-gunkan-salmone-e-uova-di-salmone.jpg', array[]::text[], array[]::text[], 9),
  ('gluten-free', 'Gunkan Philadelphia - salmone e top di tartare di salmone', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-gunkan-philadelphia-salmone-e-top-di-tartare-di-salmone.jpg', array[]::text[], array[]::text[], 10),
  ('gluten-free', 'Hosomaki Riso e Salmone', '', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 11),
  ('gluten-free', 'Hosomaki Riso e Tonno', '', 0, 'ayce', null, array[]::text[], array[]::text[], 12),
  ('gluten-free', 'Hosomaki Ricciola', '', 0, 'ayce', null, array[]::text[], array[]::text[], 13),
  ('gluten-free', 'Hosomaki Riso e Avocado', '', 0, 'ayce', null, array[]::text[], array[]::text[], 14),
  ('gluten-free', 'Hosomaki Riso e Mango', '', 0, 'ayce', null, array[]::text[], array[]::text[], 15),
  ('gluten-free', 'Philadelphia Roll', '-Salmone; -Avocado; -Philadelphia.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-philadelphia-roll.jpg', array['abbattuti']::text[], array['gluten_free']::text[], 16),
  ('gluten-free', 'Riso bianco e sesamo', '-Riso in bianco accompagnato da mix di sesamo.', 0, 'ayce', null, array[]::text[], array['vegetariano','gluten_free']::text[], 17),
  ('gluten-free', 'Noto', 'Tonno, avocado, guacamole e pomodorini', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-noto.jpg', array['abbattuti']::text[], array[]::text[], 18),
  ('gluten-free', 'Nigiri Ricciola', '', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-nigiri-ricciola.jpg', array[]::text[], array[]::text[], 19),
  ('gluten-free', 'Salmon Roll', 'Salmone, avocado e sesamo', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-salmon-roll.jpg', array['abbattuti']::text[], array[]::text[], 20),
  ('gluten-free', 'Tuna Roll', 'Tonno, avocado e sesamo', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-tuna-roll.jpg', array['abbattuti']::text[], array[]::text[], 21),
  ('gluten-free', 'Tartufo roll', 'Salmone, avocado, philadelphia e perle di tartufo nero', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-tartufo-roll.jpg', array['abbattuti']::text[], array[]::text[], 22),
  ('gluten-free', 'Patrick roll', 'Tonno, zest di lime e mandorle', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-patrick-roll.jpg', array['abbattuti']::text[], array[]::text[], 23),
  ('gluten-free', 'Guacamole sake', 'Salmone, avocado, top di guacamole', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/gluten-free-guacamole-sake.jpg', array[]::text[], array['gluten_free']::text[], 24),
  ('cucina', 'Fried Rice Gamberi', '-Riso saltato con gamberi e verdure.', 0, 'ayce', null, array['abbattuti']::text[], array[]::text[], 1),
  ('cucina', 'Noodles Pesce e Verdure', '-Spaghetti di grano saraceno con pesce e verdure.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/noodles-pesce-e-verdure.jpg', array['abbattuti']::text[], array[]::text[], 2),
  ('cucina', 'Riso bianco e sesamo', '-Riso in bianco accompagnato da mix di sesamo.', 0, 'ayce', null, array[]::text[], array['vegetariano','gluten_free']::text[], 3),
  ('cucina', 'Noodles verdure', '', 0, 'ayce', null, array[]::text[], array[]::text[], 4),
  ('cucina', 'Noodles Spicy', 'Noodles di grano saraceno piccanti, con pesce misto e verdure.', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/noodles-spicy.jpg', array[]::text[], array[]::text[], 5),
  ('cucina', 'Udon Gamberi e Verdure', 'Udon saltati in padella con gamberi, uova e verdure', 0, 'ayce', 'https://ddtkruaektfbaaqwedwo.supabase.co/storage/v1/object/public/menu-photos/udon-gamberi-e-verdure.jpg', array['surgelati']::text[], array[]::text[], 6),
  ('dolci-e-digestivi', 'Cheesecake al pistacchio', '-Cheesecake con sopra toping di pistacchio.', 700, 'carta', null, array[]::text[], array['vegetariano']::text[], 1),
  ('dolci-e-digestivi', 'Cheesecake al cioccolato', '-Cheesecake con sopra toping al cioccolato.', 600, 'carta', null, array[]::text[], array['vegetariano']::text[], 2),
  ('dolci-e-digestivi', 'Cheesecake ai frutti di bosco', '-Cheesecake con sopra toping di frutti di bosco.', 700, 'carta', null, array[]::text[], array['vegetariano']::text[], 3),
  ('dolci-e-digestivi', 'Cuore caldo al cioccolato', 'tortino al cioccolato dal cuore morbido', 700, 'carta', null, array[]::text[], array[]::text[], 4),
  ('dolci-e-digestivi', 'cheesecake al caramello', '', 700, 'carta', null, array[]::text[], array[]::text[], 5),
  ('dolci-e-digestivi', 'caffe', '', 150, 'carta', null, array[]::text[], array[]::text[], 6),
  ('dolci-e-digestivi', 'malvasia delle lipari', '>é un vino bianco dolce passito e aromatico perfetto da abbinare al dolce', 600, 'carta', null, array[]::text[], array[]::text[], 7),
  ('dolci-e-digestivi', 'coppa di gelato', 'tre palline di gelato', 600, 'carta', null, array[]::text[], array[]::text[], 8),
  ('dolci-e-digestivi', 'brownie e gelato', 'brownie al cioccolato accompanato da morbidissimo gelato alla crema', 700, 'carta', null, array[]::text[], array[]::text[], 9),
  ('dolci-e-digestivi', 'profitterol al cioccolato', '3pz (momentaneamente solo in via del bosco)', 700, 'carta', null, array[]::text[], array[]::text[], 10),
  ('dolci-e-digestivi', 'jefferson', 'un liquore amaro artigianale calabrese, realizzato con erbe, agrumi e spezie locali', 500, 'carta', null, array[]::text[], array[]::text[], 11),
  ('dolci-e-digestivi', 'grappa di moscato Sibona', 'retrogusto delicatamente dolce e persistente', 600, 'carta', null, array[]::text[], array[]::text[], 12),
  ('dolci-e-digestivi', 'grappa bocchino', 'profumo di more, spezie, iris, con un sottile tocco di gelsomino sapore con sentori di albicocche essiccate, vaniglia e mandorle tostate', 700, 'carta', null, array[]::text[], array[]::text[], 13),
  ('cocktail', 'Gin Mare', '', 1000, 'carta', null, array[]::text[], array[]::text[], 1),
  ('cocktail', 'Mojito', '', 800, 'carta', null, array[]::text[], array[]::text[], 2),
  ('cocktail', 'Negroni', '', 700, 'carta', null, array[]::text[], array[]::text[], 3),
  ('cocktail', 'Margarita', '', 700, 'carta', null, array[]::text[], array[]::text[], 4),
  ('cocktail', 'Aperol Spritz', '', 800, 'carta', null, array[]::text[], array[]::text[], 5),
  ('cocktail', 'Hugo Spritz', '', 900, 'carta', null, array[]::text[], array[]::text[], 6),
  ('cocktail', 'Negroni Sbagliato', '', 800, 'carta', null, array[]::text[], array[]::text[], 7),
  ('cocktail', 'Negrosky', '', 800, 'carta', null, array[]::text[], array[]::text[], 8),
  ('cocktail', 'gin cubical kiss', '', 1200, 'carta', null, array[]::text[], array[]::text[], 9),
  ('cocktail', 'gin ETSU', '', 1200, 'carta', null, array[]::text[], array[]::text[], 10),
  ('cocktail', 'ukiyo japanese blossom gin', '', 1200, 'carta', null, array[]::text[], array[]::text[], 11),
  ('cocktail', 'gunpowder Irish Gin drumshanbo', '', 1200, 'carta', null, array[]::text[], array[]::text[], 12),
  ('cocktail', 'rossini 2.0', '', 900, 'carta', null, array[]::text[], array[]::text[], 13),
  ('cocktail', 'cubical ultra premium dry gin', '', 1200, 'carta', null, array[]::text[], array[]::text[], 14),
  ('cocktail', 'gin coca leaf black amuerte', '', 1300, 'carta', null, array[]::text[], array[]::text[], 15),
  ('bevande-e-birre', 'Cristalli Di sale cl33', '', 400, 'carta', null, array[]::text[], array[]::text[], 1),
  ('bevande-e-birre', 'Coca Cola 33cl', '', 350, 'carta', null, array[]::text[], array[]::text[], 2),
  ('bevande-e-birre', 'Birra Asahi 33cl', '', 400, 'carta', null, array[]::text[], array[]::text[], 3),
  ('bevande-e-birre', 'Acqua Naturale', '', 300, 'carta', null, array[]::text[], array[]::text[], 4),
  ('bevande-e-birre', 'Acqua Frizzante', '', 300, 'carta', null, array[]::text[], array[]::text[], 5),
  ('bevande-e-birre', 'Sprite', '', 350, 'carta', null, array[]::text[], array[]::text[], 6),
  ('bevande-e-birre', 'Acqua Leggermente frizzante', '', 300, 'carta', null, array[]::text[], array[]::text[], 7),
  ('bevande-e-birre', 'Kirin Ichiban 50cl', '', 650, 'carta', null, array[]::text[], array[]::text[], 8),
  ('bevande-e-birre', 'Fanta', '', 350, 'carta', null, array[]::text[], array[]::text[], 9),
  ('bevande-e-birre', 'Asahi 50 cl', '', 650, 'carta', null, array[]::text[], array[]::text[], 10),
  ('bevande-e-birre', 'Calice Di Vino', '', 800, 'carta', null, array[]::text[], array[]::text[], 11),
  ('vino-bianco', 'Patrì - Disìo (Frizzante)', '', 3200, 'carta', null, array[]::text[], array[]::text[], 1),
  ('vino-bianco', 'Pinot Grigio - Ca'' Bolani', '', 3000, 'carta', null, array[]::text[], array[]::text[], 2),
  ('vino-bianco', 'Scialàri - Principi di Butera (Frizzante)', '', 3200, 'carta', null, array[]::text[], array[]::text[], 3),
  ('vino-bianco', 'Chardonnay - Ca'' Bolani', '', 3000, 'carta', null, array[]::text[], array[]::text[], 4),
  ('vino-bianco', 'Traminer Aromatico - Ca'' Bolani', '', 3000, 'carta', null, array[]::text[], array[]::text[], 5),
  ('vino-bianco', 'Principi di Butera, Diamanti - Grillo 2024', '', 3000, 'carta', null, array[]::text[], array[]::text[], 6),
  ('vino-bianco', 'Masseria Altemura - Zìnzula 2023', '', 3200, 'carta', null, array[]::text[], array[]::text[], 7),
  ('vino-bianco', 'Case Alte - Filari Grillo 2023 Bio', '', 3600, 'carta', null, array[]::text[], array[]::text[], 8),
  ('vino-bianco', 'Case Alte - Monreale Bianco 2024 Bio', '', 3600, 'carta', null, array[]::text[], array[]::text[], 9),
  ('vino-bianco', 'Patria - Sensi - Etna Bianco 2024', '', 3200, 'carta', null, array[]::text[], array[]::text[], 10),
  ('bollicine', 'Ca'' Bolani - Prosecco Brut', '', 3200, 'carta', null, array[]::text[], array[]::text[], 1),
  ('fine-pasto', 'Amaro del capo', '', 400, 'carta', null, array[]::text[], array[]::text[], 1),
  ('fine-pasto', 'Amaro jagermeister', '', 400, 'carta', null, array[]::text[], array[]::text[], 2),
  ('fine-pasto', 'Amaro Amara', '', 400, 'carta', null, array[]::text[], array[]::text[], 3),
  ('fine-pasto', 'Caffè', '', 150, 'carta', null, array[]::text[], array[]::text[], 4),
  ('vini-rosati', 'Fina Hanami Rosè 2022', '', 3000, 'carta', null, array[]::text[], array[]::text[], 1),
  ('vini-rosati', 'Masseria Altemura, Zinzula Rosè 2023', '', 3000, 'carta', null, array[]::text[], array[]::text[], 2),
  ('vini-rosati', 'Navarra- Disiata Frappato Rosato 2024', '', 3000, 'carta', null, array[]::text[], array[]::text[], 3),
  ('vini-rosati', 'Tenuta La Favola - Chidormenonpigliapesci Rosato', '', 3000, 'carta', null, array[]::text[], array[]::text[], 4),
  ('vino-rosso', 'Cusumano - Benuara 2022', '', 3200, 'carta', null, array[]::text[], array[]::text[], 1),
  ('vino-rosso', 'Principi Di Butera - Syrah', '', 3000, 'carta', null, array[]::text[], array[]::text[], 2),
  ('vino-rosso', 'Vincenzo Trigona - Etna Rosso 2019', '', 4000, 'carta', null, array[]::text[], array[]::text[], 3),
  ('vino-rosso', 'Cusumano - Merlot 2022', '', 2800, 'carta', null, array[]::text[], array[]::text[], 4),
  ('vino-rosso', 'Bisi - Bonarda Rosso Frizzante 2023', '', 3200, 'carta', null, array[]::text[], array[]::text[], 5)
) as v(cat_slug, name, description, price_cents, menu_type, photo_url, allergens, tags, sort_order)
join cat c on c.slug = v.cat_slug;
